[project]
name = "simpleprompt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.36.24",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
]
